### ISSUE TITLE
[Feature] Import  OBJE Fields on GEDCOM Import

### ISSUE THREAD

**Issue by jeff962** [banisterious/obsidian-charted-roots#202]
## Problem / Use Case

I've been troubleshooting place names on import from the .gpkg format (it doesn't create the state and country names correctly), so I tried importing a GEDCOM file, which does import the places correctly.  I also noticed the other improvements made recently to the GEDCOM import (Given Name, Surnames, etc.) which I'd also like to leverage.

Looking at the GEDCOM file I noticed it has these OBJE fields that point to the media files. For example:

```
1 NAME Someone /Hatfield/
2 TYPE birth
...
1 FAMS @F0001@
1 SOUR @S0000@
1 OBJE @O0205@ 

Points to -->

0 @O0205@ OBJE
1 FILE /media/linuxstore/pictures/Ancestors/Hatfield/Hatfield_2022.jpg
2 FORM jpg
2 TITL Hatfield_2022
```
The only reason I've been using the .gpkg format for importing is to preserve the links to the media files.  So if the GEDCOM could import links to media files, that would be a good solution since it's smaller and faster.

My "Charted Roots/Media" folder is actually a link that points to "/media/linuxstore/pictures/Ancestors" so it should work the way it does for a .gpkg import. 

## Proposed Solution

Bring over the links to the media files on GEDCOM import.

## Alternatives Considered

Maintain functional parity between GEDCOM and Gramps import formats.

**Comment by jeff962** [comment]
After upgrading to 19.13 and importing my GEDCOM file, it looks like there's a slight problem with rendering the canvas-roots-media block. 

<img width="943" height="328" alt="Image" src="https://github.com/user-attachments/assets/2b656db2-56c8-414f-8121-8ca3710905d8" />

**Comment by banisterious** [comment]
Hmm, the error `value.trim is not a function` suggests the `media` property in your frontmatter contains a non-string value (possibly a number or object instead of a wikilink string).

Could you share the frontmatter from one of the affected notes? Specifically the `media:` property - I'd like to see exactly how it's formatted. That will help me determine if this is a GEDCOM import issue or something with how the data is being parsed.

**Comment by jeff962** [comment]
Sure thing - This is from the same note as my earlier screen shot.

```
media:
  - [[Hatfield_Jeff_2022.jpg]]
  - [[Hatfield_Jeff.jpg]]
  - [[P1000702.JPG]]
  - [[Hatfield Jeff and Martha - college.jpg]]
  - [[Hatfield Jeff waiting on new baby brother.jpg]] 
```

**Comment by banisterious** [comment]
The frontmatter looks correct - all valid wikilink strings. The fix I pushed earlier today adds defensive handling for non-string values, but your data should have worked even before.

A few follow-up questions:
1. Is this error happening on a note you just imported with 0.19.13, or one that existed before?
2. Does the error happen consistently, or only sometimes (e.g., after Obsidian starts)?
3. Are there any other `media:` entries elsewhere in the note (perhaps in a nested property or duplicate frontmatter block)?

The fix in the latest commit should prevent the crash regardless, but I'd like to understand the root cause.
